SIM ?= icarus
TOPLEVEL_LANG ?= verilog

VERILOG_SOURCES += dut.sv
VERILOG_SOURCES += controller.sv
VERILOG_SOURCES += SST25WF020A.v 

TOPLEVEL = dut 
MODULE = test_basic

include $(shell cocotb-config --makefiles)/Makefile.sim